In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix

y_true = [0, 0, 1, 1, 2, 2, 2, 0, 1, 1]
y_pred = [0, 0, 1, 1, 0, 2, 2, 0, 1, 1]


cm = confusion_matrix(y_true, y_pred)
print('Matriz de Confusão:')
print(cm)


VP = np.diag(cm)
FP = np.sum(cm, axis=0) - VP
FN = np.sum(cm, axis=1) - VP
VN = np.sum(cm) - (FP + FN + VP)

sensibilidade = VP / (VP + FN)
especificidade = VN / (FP + VN)
acuracia = (VP + VN) / (VP+FN+VN+FP)
precisao = VP / (VP + FP)
f1_score = 2 * (precisao * sensibilidade) / (precisao + sensibilidade)


print('\nMétricas por Classe:')
for i in range(len(VP)):
  print(f'Classe {i}:')
  print(f'  Sensibilidade: {sensibilidade[i]:.2f}')
  print(f'  Especificidade: {especificidade[i]:.2f}')
  print(f'  Precisão: {precisao[i]:.2f}')
  print(f'  F1-Score: {f1_score[i]:.2f}')

print(f'\nAcurácia Geral: {np.mean(acuracia):.2f}')


Matriz de Confusão:
[[3 0 0]
 [0 4 0]
 [1 0 2]]

Métricas por Classe:
Classe 0:
  Sensibilidade: 1.00
  Especificidade: 0.86
  Precisão: 0.75
  F1-Score: 0.86
Classe 1:
  Sensibilidade: 1.00
  Especificidade: 1.00
  Precisão: 1.00
  F1-Score: 1.00
Classe 2:
  Sensibilidade: 0.67
  Especificidade: 1.00
  Precisão: 1.00
  F1-Score: 0.80

Acurácia Geral: 0.93
